import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import LanguageProvider from "../providers/LanguageProvider";
import Starfield from "../components/Starfield";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <LanguageProvider>
          <div className="relative min-h-screen text-gray-300 antialiased">
            <Starfield />
            <div className="container mx-auto max-w-5xl px-6 py-8">
              <Navbar />
              {children}
            </div>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
